version = "0.1.0"
description = "A new project managed by axes."

[commands]
hello = "echo 'Hello from axes!'"
exit = "echo 'Saliendo....' && exit"
pause = "pause"
build = "{v_build}"
replace = "{v_replace}"
br = ["{v_build}", "{v_replace}", "echo 'Todo listo!'"]

[options]

[vars]
v_build = "cargo build --release"
v_replace = "copy /Y {root}\\target\\release\\axes.exe C:\\scripts\\axes.exe"

[env]
